channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - molmod =1.4.8
  - numpy =1.20.3
  - pyiron_atomistics =0.2.15
  - scipy =1.6.3
  - spglib =1.16.1
  - quickff =2.2.4
  - tamkin =1.2.6
  - yaff =1.4.2
