channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- molmod =1.4.8
- numpy =1.26.2
- pyiron_atomistics =0.3.10
- scipy =1.11.4
- spglib =2.1.0
- quickff =2.2.4
- tamkin =1.2.6
- yaff =1.6.0
