channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- molmod =1.4.8
- numpy =1.21.1
- pyiron_atomistics =0.2.22
- scipy =1.7.1
- spglib =1.16.2
- quickff =2.2.4
- tamkin =1.2.6
- yaff =1.4.2
