channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - molmod =1.4.8
  - numpy =1.20.1
  - pyiron_atomistics =0.2.7
  - scipy =1.6.0
  - spglib =1.16.1
  - sqlalchemy =1.3.23  # 1.4.0 is broken on conda
  - quickff =2.2.4
  - tamkin =1.2.6
  - yaff =1.4.2
