channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- molmod =1.4.8
- numpy =1.22.2
- pyiron_atomistics =0.2.36
- scipy =1.8.0
- spglib =1.16.3
- quickff =2.2.4
- tamkin =1.2.6
- yaff =1.4.2
