channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- molmod =1.4.8
- numpy =1.24.3
- pyiron_atomistics =0.2.65
- scipy =1.10.1
- spglib =2.0.2
- quickff =2.2.4
- tamkin =1.2.6
- yaff =1.6.0
