# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: "3.11"
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: .ci_support/environment.yml
        miniforge-variant: Mambaforge
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      run: |
        coverage run --omit pyiron_atomistics/_version.py -m unittest discover tests
        coverage xml
    - name: Coveralls
      if: matrix.label == 'linux-64-py-3-11'
      uses: coverallsapp/github-action@v2
    - name: Codacy
      if: matrix.label == 'linux-64-py-3-11' && github.event_name != 'push'
      continue-on-error: True
      shell: bash -l {0}
      run: |
        python-codacy-coverage -r coverage.xml
